opam-version: "2.0"
name: "coq-paco"
version: "dev"
synopsis: "A Coq library for parametric coinduction"
maintainer: "Chung-Kil Hur <gil.hur@gmail.com>"
license: "BSD-3-Clause"
homepage: "https://github.com/snu-sf/paco"
bug-reports: "https://github.com/snu-sf/paco/issues"
dev-repo: "git+https://github.com/snu-sf/paco.git"

depends: [
  "rocq-core" {>= "9.0"}
  "rocq-stdlib"
]

build: [make "-C" "src" "all" "-j%{jobs}%"]
install: [make "-C" "src" "-f" "Makefile.coq" "install"]
